define(function(require){var $=require("jquery");var hoganpower=require("hoganpower");var conf=require("lmd/core/conf");var context=require("lmd/core/context");var service=require("lmd/core/service");var storage=require("lmd/core/storage");var objectPath=require("lib/object-path");var isWww=context.application==="www";var templateToaster=require("hoganpower!/templates/module/meter/toaster.html.mu");var templateWall=require("hoganpower!/templates/module/meter/wall.html.mu");var consts={readItemKey:"us_meter_readed",
activatedKey:"us_meter_activation",simulationKey:"us_meter_simulation"};return{launch:launch,simulate:simulate};function launch(){loadMeter();if(!isActivated()||!isValidPage())return;if(!canReadItem())displayWall();else{displayArticle();storeItem();displayToaster()}}function canReadItem(){var quota=objectPath.get(conf,"us_meter.quota_per_month");return lmd.usMeter.readItemIds.length<quota}function displayArticle(){var id=objectPath.get(context,"element.id");var pageType=objectPath.get(context,"pageType");
var elementType=objectPath.get(context,"element.type.nom");var isRestricted=objectPath.get(context,"element.restreint");if(/^\d+$/.test(id)&&pageType==="Element"&&elementType==="article"&&isRestricted===true){var url=["overlay",id,"us_meter"].join("/");var params={dataType:"json",timeout:1E4};service.get(url,1,{},params).then(function(json){$(".js_article_body").html(json.element);$(".js_teaser_article").detach()})}}function displayToaster(){var displayAt=objectPath.get(conf,"us_meter.display_toaster");
var readNumber=lmd.usMeter.readItemIds.length.toString();var limit=objectPath.get(conf,"us_meter.quota_per_month").toString();var toasterNumber=displayAt.indexOf(readNumber)+1;if(displayAt.indexOf(readNumber)>-1||parseInt(limit,10)===parseInt(readNumber,10)){if(objectPath.get(conf,"fsw.us_meter_display")===true){$("body").append(templateToaster.render({readNumber:readNumber,limit:limit,isLast:parseInt(readNumber,10)>=parseInt(limit,10),key:isWww?"TOASTERWEB":"TOASTERMOB",step:toasterNumber}));$(".js_meter_toaster").on("click",
".bt_fermer_rond",function(){$(".js_meter_toaster").remove()})}doTrackingHit("Affichage_Toaster::affichage_"+toasterNumber);doTrackXtView("INT-43-"+toasterNumber)}}function displayWall(){var limit=objectPath.get(conf,"us_meter.quota_per_month").toString();if(objectPath.get(conf,"fsw.us_meter_display")===true){$(".js_meter_global").append(templateWall.render({limit:limit,key:isWww?"PAYWALLWEB":"PAYWALLMOB"}));$(window).scrollTop(0);$("#video_container").remove()}doTrackingHit("Affichage_wall");doTrackXtView("INT-42")}
function isActivated(){var fswActivated=objectPath.get(conf,"fsw.us_meter");var activated=storage.get(consts.activatedKey)!==null;return fswActivated&&activated||isSimulated()}function isSimulated(){return storage.get(consts.simulationKey)!==null}function isValidPage(){var application=objectPath.get(conf,"us_meter.application")||[];var pageType=objectPath.get(conf,"us_meter.page_type")||[];return application.indexOf(context.application)>-1&&pageType.indexOf(context.pageType)>-1}function loadMeter(){var readItemIds=
JSON.parse(storage.get(consts.readItemKey))||[];window.lmd=lmd||{};window.lmd.usMeter={activated:isActivated(),simulated:isSimulated(),readItemIds:readItemIds}}function simulate(activation){if(activation===true){storage.set(consts.simulationKey,true);console.debug("US Meter simulation activated")}else{storage.remove(consts.simulationKey);console.debug("US Meter simulation desactivated")}loadMeter()}function storeItem(){window.lmd=lmd||{};lmd.usMeter.readItemIds=lmd.usMeter.readItemIds||[];if(lmd.usMeter.readItemIds.indexOf(context.item.id)===
-1){lmd.usMeter.readItemIds.push(context.item.id);storage.set(consts.readItemKey,JSON.stringify(lmd.usMeter.readItemIds),dataTimeout())}}function doTrackingHit(click_name){if(typeof window.xt_med==="function")window.xt_med("C","",click_name,"A")}function dataTimeout(){var now=new Date;var lastDay=new Date(now.getFullYear(),now.getMonth()+1,0,23,59,59);return lastDay-now}function doTrackXtView(id){$("<img/>").appendTo("body").attr("src","http://logc2.xiti.com/get.ad?xts=43260&ati="+id+"&type=AT&z="+
(new Date).getTime())}});
