define(function(){if(!window["lzld"])(function(window,document){var winH=viewport(),imgs=[],pageHasLoaded=false,unsubscribed=false,saveViewportT=throttle(viewport,20),showImagesT=throttle(showImages,20);window["lzld"]=onDataSrcImgLoad;window["lzld"]["config"]={retina:"auto",hdCallback:defaultHdCallback,lazyAttr:"data-src",minDevicePixelRatio:1.5,offset:200};window["lzld"]["update"]=update;dataNoHDAttr="data-no-hd-src",dataHDAttr="data-hd-src";function isRetinaDevice(){var pixelRatio=typeof window.devicePixelRatio!==
"undefined"?window.devicePixelRatio:1;return pixelRatio>=window.lzld.config.minDevicePixelRatio}window["lzld"]["isRetinaDevice"]=isRetinaDevice;domready(findImages);addEvent(window,"load",onLoad);subscribe();function onDataSrcImgLoad(img){if(inArray(img,imgs)===-1){if(unsubscribed)subscribe();showIfVisible(img,imgs.push(img)-1)}}function findImages(){var domreadyImgs=document.getElementsByTagName("img"),currentImg;for(var imgIndex=0,max=domreadyImgs.length;imgIndex<max;imgIndex+=1){currentImg=domreadyImgs[imgIndex];
if(currentImg.getAttribute(window.lzld.config.lazyAttr)&&inArray(currentImg,imgs)===-1)imgs.push(currentImg)}showImages();setTimeout(showImagesT,25)}function onLoad(){pageHasLoaded=true;showImagesT();setTimeout(showImagesT,25)}function throttle(fn,minDelay){var lastCall=0;return function(){var now=+new Date;if(now-lastCall<minDelay)return;lastCall=now;fn.apply(this,arguments)}}function addEvent(el,type,fn){if(el.attachEvent)el.attachEvent&&el.attachEvent("on"+type,fn);else el.addEventListener(type,
fn,false)}function removeEvent(el,type,fn){if(el.detachEvent)el.detachEvent&&el.detachEvent("on"+type,fn);else el.removeEventListener(type,fn,false)}function domready(callback){var done=false,top=true;function init(e){if(e.type==="readystatechange"&&document.readyState!=="complete")return;removeEvent(e.type==="load"?window:document,e.type,init);if(!done){done=true;callback()}}function poll(){try{document.documentElement.doScroll("left")}catch(e){setTimeout(poll,50);return}init("poll")}if(document.readyState===
"complete")callback();else{if(document.createEventObject&&document.documentElement.doScroll){try{top=!window.frameElement}catch(e){}if(top)poll()}addEvent(document,"DOMContentLoaded",init);addEvent(document,"readystatechange",init);addEvent(window,"load",init)}}function showIfVisible(img,index){if(contains(document.documentElement,img)&&img.getBoundingClientRect().top<winH+window.lzld.config.offset){img.onload=null;img.removeAttribute("onload");img.onerror=null;img.removeAttribute("onerror");var attr=
img.getAttribute(window.lzld.config.lazyAttr)?window.lzld.config.lazyAttr:"src",src=img.getAttribute(attr);if(window.lzld.config.retina===true||window.lzld.config.retina==="auto"&&isRetinaDevice())if(!img.getAttribute(dataHDAttr)){img.setAttribute(dataNoHDAttr,src);if(typeof window.lzld.config.hdCallback==="function")src=window.lzld.config.hdCallback(img.getAttribute(attr));img.setAttribute(dataHDAttr,src)}else src=img.getAttribute(dataHDAttr);else if(!img.getAttribute(dataNoHDAttr)){var noHDSrc=
img.getAttribute(dataNoHDAttr);if(noHDSrc)src=noHDSrc}else src=img.getAttribute(dataNoHDAttr);img.setAttribute(window.lzld.config.lazyAttr,src);img.src=img.getAttribute(window.lzld.config.lazyAttr);img.removeAttribute(window.lzld.config.lazyAttr);imgs[index]=null;return true}else return false}function defaultHdCallback(src){var srcSegments=src.split("."),srcWithoutExtension=srcSegments.slice(0,srcSegments.length-1).join("."),extension=srcSegments[srcSegments.length-1];return srcWithoutExtension+"@2x."+
extension}function viewport(){if(document.documentElement.clientHeight>=0)return document.documentElement.clientHeight;else if(document.body&&document.body.clientHeight>=0)return document.body.clientHeight;else if(window.innerHeight>=0)return window.innerHeight;else return 0}function saveViewport(){winH=viewport()}function showImages(){var last=imgs.length,current,allImagesDone=true;for(current=0;current<last;current++){var img=imgs[current];if(img!==null&&!showIfVisible(img,current))allImagesDone=
false}if(allImagesDone&&pageHasLoaded)unsubscribe()}function unsubscribe(){unsubscribed=true;removeEvent(window,"resize",saveViewportT);removeEvent(window,"scroll",showImagesT);removeEvent(window,"load",onLoad)}function subscribe(){unsubscribed=false;addEvent(window,"resize",saveViewportT);addEvent(window,"scroll",showImagesT)}function contains(){}contains=document.documentElement.compareDocumentPosition?function(a,b){return!!(a.compareDocumentPosition(b)&16)}:document.documentElement.contains?function(a,
b){return a!==b&&(a.contains?a.contains(b):false)}:function(a,b){while(b=b.parentNode)if(b===a)return true;return false};function inArray(elem,array,i){var len;if(array){if(Array.prototype.indexOf)return Array.prototype.indexOf.call(array,elem,i);len=array.length;i=i?i<0?Math.max(0,len+i):i:0;for(;i<len;i++)if(i in array&&array[i]===elem)return i}return-1}function update(){showImages()}})(this,document);return window.lzld});
